version: "2"

volumes:
  peer2-org1:
  couchdb2-org1:

networks:
  ca_net:
    external: true

services:
  couchdb2-org1:
    container_name: couchdb2-org1
    image: hyperledger/fabric-couchdb:0.4.18
    restart: always
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - ca_net
    ports:
      - 6984:5984
    volumes:
      - couchdb2-org1:/opt/couchdb/data

  peer2-org1:
    container_name: peer2-org1
    image: hyperledger/fabric-peer:1.4.4
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ca_net
      - CORE_PEER_ID=peer2-org1
      - CORE_PEER_ADDRESS=peer2-org1:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer2-org1:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_PROFILE_ENABLED=true
      # Gossip
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org1:8051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/tls.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/tls.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/cacerts/ca-tls.pem
      # Couch DB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2-org1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto/peer2/msp:/etc/hyperledger/fabric/msp
      - ./crypto/peer2/tls:/etc/hyperledger/fabric/tls
      - peer2-org1:/var/hyperledger/production
    networks:
      - ca_net
    depends_on:
      - couchdb2-org1