version: '2'

networks:
  ca_net:
    external: true

services:
  rca-org2:
    container_name: rca-org2
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/tmp/hyperledger/fabric-ca/crypto/ca-cert.pem
      - FABRIC_CA_CLIENT_HOME=/tmp/hyperledger/fabric-ca/admin
      - FABRIC_CA_SERVER_CSR_CN=rca-org2
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org2
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./data:/tmp/hyperledger/fabric-ca
    working_dir: /tmp/hyperledger/fabric-ca
    networks:
      - ca_net
    ports:
      - 7055:7054