version: '2'

networks:
  ca_net:
    external: true

services:
  rca-org0:
    container_name: rca-org0
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./data:/tmp/hyperledger/fabric-ca
    networks:
      - ca_net
    ports:
      - 7053:7052